# Generated by Django 4.1.2 on 2022-10-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_dress'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='accessories',
            field=models.ManyToManyField(to='main_app.accessory'),
        ),
        migrations.AddField(
            model_name='dress',
            name='qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dress',
            name='color',
            field=models.CharField(max_length=100),
        ),
    ]
