# Generated by Django 4.1.2 on 2022-10-22 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_dress_accessories_remove_dress_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='dress',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.dress'),
            preserve_default=False,
        ),
    ]
