# Generated by Django 4.1.2 on 2022-10-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_dress_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
